### ISSUE TITLE
Making main.rb executable from Team #132

### ISSUE THREAD

**Issue by Prabhakarzx** [RaminMammadzada/ruby-tic-tac-toe-game#5]
# Hello Team! :handshake: 
##### Here are a few resources which may help you! :man_technologist: 

- https://commandercoriander.net/blog/2013/02/16/making-a-ruby-script-executable/
- https://www.vikingcodeschool.com/falling-in-love-with-ruby/running-ruby-scripts
- https://stackoverflow.com/questions/14724250/how-can-i-execute-a-ruby-script-as-executable-file

**Comment by Berabjesus** [comment]
Suggestions
: - Add a loop or a method that iterates for a new game.

**Comment by RaminMammadzada** [comment]
> # Hello Team! 🤝
> ### Awesome that you've figure out most of things in the milestone 1 💯
> ##### Here are a few resources which may help you! 👨‍💻
> * https://commandercoriander.net/blog/2013/02/16/making-a-ruby-script-executable/
> * https://www.vikingcodeschool.com/falling-in-love-with-ruby/running-ruby-scripts
> * https://stackoverflow.com/questions/14724250/how-can-i-execute-a-ruby-script-as-executable-file

Thank you for creating an issue, I have solved it. You can check it in ```setup``` branch.

**Comment by RaminMammadzada** [comment]
> Suggestions
> : - Add a loop or a method that iterates for a new game.

We will add it soon, you can follow it in ```develop```branch.
