### ISSUE TITLE
peer to peer review 20-08-2020

### ISSUE THREAD

**Issue by mikethreels** [RaminMammadzada/ruby-tic-tac-toe-game#6]
Hi Guys, 

your project looks great so far, maybe take the below suggestion into consideration.
- try not to us classes inside your main.rb file

great job!
team 122-the-manx

**Comment by RaminMammadzada** [comment]
The issue is fixed. You can check [develop](https://github.com/RaminMammadzada/ruby-tic-tac-toe-game/tree/develop) branch.
