### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by mimipeshy** [RaminMammadzada/ruby-tic-tac-toe-game#9]
Hi Sajad and RaminMammadzada,
Great work you did with refactoring the main file and separating the classes. Just check on the TSE review and work on the changes like using require_relative instead of require and add more comments to the 'game' to catch errors. All the best and Happy coding !!!!!

Regards 
Peris Ndanu
#team122-the-manx

**Comment by RaminMammadzada** [comment]
The issue is fixed. You can check [develop](https://github.com/RaminMammadzada/ruby-tic-tac-toe-game/tree/develop) branch.

**Comment by RaminMammadzada** [comment]
The issue is fixed. You can check [develop](https://github.com/RaminMammadzada/ruby-tic-tac-toe-game/tree/develop) branch.
